### PR TITLE
printing hex values instead of decimals for raw modbus logging

### PR DESCRIPTION
**Pull request by gonium**
I'm using your library to create an interface for an Eastron SDM630-Modbus electricity meter. During development I find it easier to look at hexadecimal dumps of the data packets - which is what I implemented here.

### CODE REVIEW

**Comment by nqv** [comment]
How about using `%x`?

**Comment by gonium** [comment]
Actually, I prefer ````%#v````: ````[]byte{0x1, 0x4, 0x0, 0x0, 0x0, 0x2, 0x71, 0xcb}```` is easier to read than ````01040000000271cb```` (as with ````%x````). But I guess this is a matter of personal taste.

**Comment by nqv** [comment]
I've changed format to `% x`, which will print `01 04 00 00 00 02 71 cb`.

**Comment by gonium** [comment]
that is even better. thanks!

**Pull request closed without merging**
