### PR TITLE
fix one bug createfile once error: gle=5

### PR DESCRIPTION
**Pull request by tensafe**
when run on windows 8, app may call createfile once, then failed.
gle=5,then no data can read...

### CODE REVIEW

**Comment by tensafe** [comment]
```
// as
package main

import (
	"fmt"
	"github.com/goburrow/modbus"
	"log"
	"os"
	"time"
)

func TestRtuClient() {
	handler := modbus.NewRTUClientHandler("\\\\.\\com1")
	handler.Timeout = 5 * time.Second
	handler.SlaveId = 1
	handler.BaudRate = 19200
	handler.DataBits = 8
	handler.Parity = "N"
	handler.StopBits = 1

	handler.Logger = log.New(os.Stdout, "test: ", log.LstdFlags)

	err := handler.Connect()

	defer handler.Close()

	client := modbus.NewClient(handler)

	result, err := client.ReadHoldingRegisters(0, 3)

	if err == nil {
		fmt.Println(result)
	} else {
		fmt.Println(err.Error()) //---out put error... gle:5
	}
}

func main() {
	TestRtuClient()
}

```

**Comment by nqv** [comment]
Would you please explain what the error? In your code snippet `err := handler.Connect()`, what is the `err` here?

**Comment by tensafe** [comment]
I redebug it ... find this ...
if app can read data normal, I need comment this code:
```
	err := handler.Connect()

	if err != nil {
		fmt.Println(err.Error())
	}


	defer handler.Close()
```
then I add log on serial.go func Connect like this:
```
	if mb.port == nil {
		mb.port, err = serial.Open(&mb.Config)
	} else {
		err = mb.port.Open(&mb.Config)
	}
	
	if err != nil {
		fmt.Println("Connect error:", err.Error())
	} else {
		fmt.Println("Connect ok")
	}
	
	if err != nil {
		mb.isConnected = true
	}
```
then uncommet code,output this:
```
Connect ok
Connect error: Access is denied.
Access is denied.
```

When I call handler.Connect(), inner syscall.CreateFile whith mode 0

```
	handle, err = syscall.CreateFile(
		syscall.StringToUTF16Ptr(c.Address),
		syscall.GENERIC_READ|syscall.GENERIC_WRITE,
		0,   // mode <-----------------------------------
		nil, // security
		syscall.OPEN_EXISTING, // create mode
		0, // attributes
		0) // templates
```
then call other api...

when run to serial.go func Connect, don't set mb.isConnected = true

so..next call ReadHoldingRegisters, recall CreateFile.... then ret lasterror=5

**Comment by nqv** [comment]
My bad. Would you mind to run `go get -u github.com/goburrow/modbus` and check if it's now working properly with your machine. It must be fixed in 8b151e5eecacb1e3b.
Thanks.

**Pull request closed without merging**
