### PR TITLE
Add link recovery on EOF for TCP header

### PR DESCRIPTION
**Pull request by gq0**
Continues #24

### CODE REVIEW

**Comment by andig** [comment]
ping @gq0 I'm having the same problem. Is your repo still available?

**Comment by gq0** [comment]
Sure https://github.com/grid-x/modbus
We added some minor fixes, link and protocol recovery

**Comment by andig** [comment]
Great, thank you. I had ported your PR (repo link in gh was broken) to my fork and didn't see an improvement. How should Link/ProtocolRecoveryTimeout be initialized for this to work?

**Comment by gq0** [comment]
Depending on the issue you face, you should set `LinkRecoveryTimeout` to 10 or more seconds if you see TCP timeouts or `ProtocolRecoveryTimeout` to 10 seconds or more if you have issues with Modbus transaction IDs or malformed CRC. Create your handler as usual with `NewTCPClientHandler` and set these two timeouts according to your issue, e.g. `LinkRecoveryTimeout = 60s` and `ProtocolRecoveryTimeout = 10s`.

BTW what kind of Modbus device you want communicates with?

**Comment by andig** [comment]
Its a SolarEdge Se9k. Sometimes it doesn‘t like answering right from the beginnen...

**Comment by gq0** [comment]
I see SolarEdge 😀 yeah it has both problems, links (TCP) and protocol (modbus transaction id).

**Comment by andig** [comment]
Ok, I'll need to test this again with proper timeouts. Would you be interested in maintaining your fork with additional PRs while #25, #33, #36 are open here in master?

**Comment by gq0** [comment]
You can redirect your PR to https://github.com/grid-x/modbus if you like. But I cannot guaranty that all will fit to our existing code base. But we definitely will have a look.

**Comment by andig** [comment]
> You can redirect your PR to https://github.com/grid-x/modbus if you like.

Would like to but its apparently not that easy since grid-x was not forked from goburrow. I'll need to double-check how to do that.

**Comment by ilikui** [comment]
Closed .

**Comment by ilikui** [comment]
Closed .

**Pull request closed without merging**
